---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeserver-deploy
  namespace: codeserverns
  labels:
    app: codeserver
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: codeserver
      name: codeserver-po
  template:
    metadata:
      name: codeserver-po
      namespace: codeserverns
      labels:
        app: codeserver
        name: codeserver-po
    spec:
      volumes:
        - name: workspace-vol
          persistentVolumeClaim:
            claimName: codeserver-pvc
      containers:
        - name: codeserver-container
          image: linuxserver/code-server:amd64-4.95.3
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef: 
                name: codeserver-cm
            - secretRef: 
                name: codeserver-secret
          volumeMounts:
            - name: workspace-vol
              mountPath: /config/workspace
          ports:
            - containerPort: 8443
          resources:
            requests:
              memory: 512M # Changed from 256M
              cpu: 200m
            limits:
              memory: 512M # Changed from 256M
              cpu: 200m

---
apiVersion: v1
kind: Service
metadata:
  name: codeserver-svc
  namespace: codeserverns
  labels:
    app: codeserver
spec:
  type: ClusterIP
  selector:
    app: codeserver
  ports:
    - name: codeserver
      port: 8443
      targetPort: 8443

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codeserver-ing
  namespace: codeserverns
  labels:
    app: codeserver
spec:
  ingressClassName: nginx
  rules:
    - host: code-137.184.249.10.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix # Can also do Exact, ImplementationSpecific. ImplementationSpecific means the path will be passed to the controller for interpretation
            backend:
              service:
                name: codeserver-svc
                port:
                  number: 8443
