---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  namespace: bggns
  labels:
    app: bggapp-deploy
spec:
  replicas: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: bggapp-deploy
  template:
    metadata:
      name: bggapp-po
      namespace: bggns
      labels:
        app: bggapp-deploy
    spec:
      containers:
        - name: bggapp-backend
          image: stackupiss/bgg-backend:v2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            periodSeconds: 60
          envFrom:
            - configMapRef:
                name: bgg-cm
            - secretRef:
                name: bgg-secret
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
  labels:
    app: bgg
spec:
  type: ClusterIP
  selector:
    app: bggapp-deploy
  ports:
    - name: app
      port: 8080
      targetPort: 3000